name: Workflow Hello World
on:
  push:
    branches:
      - helloworldbranch
      
  workflow_dispatch: null
  
jobs:
  my_hello_world_job:
    name: Exploring actions
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: amaryan96/githubactionstest
        always_pull: true
        cache_froms: amaryan96/githubactionstest:latest
        tags: latest



