name: Workflow Hello World
'on':
  push: null
  branches:
    - helloworldbranch
  workflow_dispatch: null
jobs:
  my_hello_world_job: null
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Ejecutar comandos
  run: echo hello world
